README improvements, added example
jbreitbart/criterion-perf-events pull request #11
Opened 2021-05-22 15:03 UTC by Anton-4

Thanks for this cool plugin!
It did take me a while to find my bearings, so I thought I'd help make this easier for the next person.

@jbreitbart  I hope you don't mind me getting to a PR right away, I'm perfectly willing to change things as you see fit.

2021-05-22 15:04 UTC, Anton-4 commented on Cargo.toml
> +perfcnt = "0.7"
This should automatically get the last patch for 0.7.

2021-05-22 15:04 UTC, Anton-4 commented on Cargo.toml
> +harness = false
To make it easy to run the example.

2021-05-22 15:07 UTC, Anton-4 commented on README.md
> +The following code shows how to count retired instructions.
I went with instructions instead of cache-misses because on my machine there was no statistically significant difference in cache misses for the fast and slow Fibonacci versions.

2021-05-22 15:08 UTC, Anton-4 commented on README.md
> +
I simplified the README example a bit but made it self-contained for the best user experience. The benchmark in the examples folder compared two fibonacci implementations.

2021-05-22 15:10 UTC, Anton-4 commented on README.md
> -    }
In the latest version of criterion this errored often and took a long time so I just went with a fixed argument.

2021-05-22 15:11 UTC, Anton-4 commented on README.md
> +        b.iter(|| fibonacci_slow(black_box(fibo_arg)))
`black_box` prevents the compiler from optimizing this and thus distorting the benchmark results.

2021-05-22 15:11 UTC, Anton-4 commented on README.md
> +cargo criterion --message-format json
I wasn't sure where to find the perf measurements at first, this should help :)

2021-05-24 09:42 UTC, jbreitbart requested changes
Thanks a lot for the cleanup. 😄 I just added a few questions, but in general this definitively improves the usability.

2021-05-24 09:42 UTC, jbreitbart commented on Cargo.toml
> +perfcnt = "0.7"
Can you undo that change? The dependencies are automatically managed by dependabot.

2021-05-24 09:42 UTC, jbreitbart commented on README.md
```suggestion
For further details please take a look at the following [link](https://superuser.com/questions/980632/run-perf-without-root-rights).
```

2021-05-24 09:42 UTC, jbreitbart commented on Cargo.toml
> +harness = false
Thanks a lot, that makes it easier to use. Can you add a newline to the end of the file?

2021-05-24 09:42 UTC, jbreitbart commented on README.md
> +cargo criterion --message-format json
I am not sure if using the json output by default in the readme is a good idea. I haven't tried it recently, but if I remember correctly just calling cargo criterion creates graph with html files to view them in the criterion subdirectory. Has this behavior changed or are you looking for the raw results?

2021-05-24 10:09 UTC, Anton-4 commented on README.md
> +cargo criterion --message-format json
You are correct. In the report they always talk about cycles so I thought it wasn't recording the measured value, but it is. It's just always calling it cycles. I'll clarify this in the README and remove the message-format arg.

2021-05-25 12:37 UTC, jbreitbart approved these changes
Thanks a lot!

2021-05-25 13:42 UTC, merged